### ISSUE TITLE
Flickering with Bootstrap Table

### ISSUE THREAD

**Issue by kentcdodds** [a5hik/ng-sortable#132]
Hi! Excited to use this library! But I'm having difficulty implementing it with a bootstrap table. Could you help? Here's a reproduction in a jsbin: http://jsbin.com/quxuwe/edit?html,js,output

The issue is that flicker that I get when I'm dragging an item from one row to the next. Not only does it look bad, but occasionally, items will get out of sync and not be dropped in the right place. Thanks in advance!

**Comment by a5hik** [comment]
Hi why can't you make this as a 'div' or an ul>li

**Comment by kentcdodds** [comment]
Is there a good reason that it wont work as a table? Here's my first attempt at using a div instead... Not sure what I'm doing wrong, but it's not working this way either... http://jsbin.com/bilefe/edit?html,js,output

**Comment by a5hik** [comment]
Hi there are lot of examples already provided.. u need refer one.

Not any big reason for not doing it for 'table', we copy the CSS of original drag element and apply it to the element that gets dragged. so it breaks there for 'table' elements. though it requires a small fix. not yet applied.

- Ashik

**Comment by kentcdodds** [comment]
I see, that makes sense... I guess I'll just have to style divs to appear like a table. Thanks.

**Comment by kentcdodds** [comment]
I could really use some help with this. What am I doing wrong? I just can't seem to get this working... http://jsbin.com/quxuwe/4/edit?html,css,output

**Comment by a5hik** [comment]
Will help you If I get some time. thanks.

**Comment by mariocasciaro** [comment]
Having the same problem here. However it seems to happen only on Chrome; on FF it works decently. If you can point me to what you think is the portion of the code responsible for the problem, I can take a look and send a PR.

**Comment by a5hik** [comment]
the PR from @jonathanhedren is merged to the source. please check If this solves the problem.

**Comment by kentcdodds** [comment]
Awesome @jonathanhedren! If you look at the [original jsbin](http://jsbin.com/quxuwe/edit?html,js,output), you'll see that now the table gets squashed. Not sure why that's happening. I'll look at it more later. Thanks.

**Comment by jonathanhedren** [comment]
.as-sortable-item, .as-sortable-placeholder {
       display: block;
    }

Your tr elements are displayed as blocks...

**Comment by kishankanugula** [comment]
I see  "Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent." in console when i am using ng-sortable for table. I could replicate this in http://jsbin.com/quxuwe/4/edit?html,css,output as well. For divs, no issue. Any work around to fix this?

**Comment by a5hik** [comment]
this should be fixed with #237

**Comment by kentcdodds** [comment]
It's not quite solved for my use case (unless I'm mistaken) https://jsbin.com/quxuwe/edit?html,output
