### ISSUE TITLE
Not working when as-sortable-item-handle inside directive with isolated scope

### ISSUE THREAD

**Issue by osadan** [a5hik/ng-sortable#93]
I ma using the ng-sortable as follows
```javascript
<section as-sortable ng-model='somedata'>
    <div ng-repeat>
       <div class='a'><div>
       <div class='b' as-sortable-item>
           <some-directive-with-isolated-scope as-sortable-item-handler>
      </div>
    </div>
</section>'
```
and I receive the following error on line 654 Uncaught TypeError: Cannot read property 'options' of undefined

//the row
```javascript 
 // (optional) Scrollable container as reference for top & left offset calculations, defaults to Document
            scrollableContainer = angular.element($document[0].querySelector(scope.sortableScope.options.scrollableContainer)).length > 0 ?
              $document[0].querySelector(scope.sortableScope.options.scrollableContainer) : $document[0].documentElement;
```
 the problem is that the sortableScope is inside the scope. itemScope

**Comment by piernik** [comment]
I've got the same problem. Can You fix it?

**Comment by a5hik** [comment]
Yes, the master copy has a fix for this issue, will update bower.

**Comment by piernik** [comment]
Please add also version number in js file

**Comment by rosslavery** [comment]
I have the same issue, and using the latest release *or* the master branch makes no difference.

If `as-sortable` and `as-sortable-item` are outside the directive, and `as-sortable-item-handle` is inside the directive, it spits out:
```
654 Uncaught TypeError: Cannot read property 'options' of undefined
```

**Comment by pascalbayer** [comment]
Please update bower with the latest version to enable correct functionality with elements that have an isolated scope.

**Comment by a5hik** [comment]
Will update the Bower version soon.

**Comment by Yeah69** [comment]
Got the current version (1.2.0) from rails-assets. Got the same problem.

Tryed to put the as-sortable-item into the isolated directive, but this lead to another problem:
scope.sortableScope.$apply(function () {
                scope.callbacks.dragEnd(dragItemInfo.eventArgs());
              });
Here callbacks is undefined.

**Comment by davidhartman** [comment]
I'm running into the same issue. Anyone have a fix for this?

**Comment by nizarmattar** [comment]
i'm stuck with this issue too.

**Comment by davidhartman** [comment]
I actually ended up going with a different sortable control that didn't have his issue.

**Comment by hannupekka** [comment]
I'm also having issue similar to this:
```html
<div data-as-sortable="callbacks" data-ng-model="items">
  <custom-directive ng-repeat="item in items" />
</div>
```
And then I'm using `data-as-sortable-item`and `data-as-sortable-item-handle` inside custom directive template.

The error I'm getting when dragging:
```
TypeError: Cannot read property 'dragStart' of undefined
```

**Comment by a5hik** [comment]
Ok will look in to it. also PRs welcome.

**Comment by adammartin1981** [comment]
@davidhartman What sortable did you end up going with in the end?

**Comment by davidhartman** [comment]
https://github.com/angular-ui/ui-sortable

**Comment by dragosprotung** [comment]
@a5hik Did you had some time to look into this ? I hit the same problem and unfortunately I do not even begin to know where to start to fix this issue

**Comment by a5hik** [comment]
@dragosprotung Let me update you, If I get a time to look in to this over the weekend.

**Comment by bojanbass** [comment]
Same issue here and I think ng-sortable should support isolated scopes. Any plans to fix this one?

**Comment by robertbl22twc** [comment]
I also ran into this issue trying to put as-sortable-item-handle in a directive with an isolated scope.

**Comment by a5hik** [comment]
This should be fixed with the latest commit, please let me know If it exists still.

**Comment by a5hik** [comment]
the master having the fix. I had tested by creating a directive with isolated scope and goes like this...
```
<as-sortable>
  <as-sortable-item>
      <isolated-directive>
         <as-sortable-item-handle>
```
and it works fine. as the issue reported in #93 is this. Please create a plunkr for your case.

- Ashik

**Comment by jedatu** [comment]
Would you be willing to share your test as a plnkr?  I believe I have a structure that matches your recommendation, but I keep getting. `item.index is not a function`   For some reason, the index function is located at `item.$parent.$parent.index`

**Comment by Darksoulsong** [comment]
@jedatu I second that, I got the same issue using:

    <as-sortable>
      <as-sortable-item>
          <isolated-directive>
             <as-sortable-item-handle>

**Comment by a5hik** [comment]
OK. Will do so.

**Comment by nizarmattar** [comment]
I solved this issue long time ago, now it works just perfect that way i want.
i don't remember what exactly was the main issue there, but here is how i used it in my app, hope this helps someone:

HTML:
```html
<div id="sortableContainer" data-as-sortable="dragControlListeners" data-ng-model="followers">
   <div ng-repeat="follower in followers" data-as-sortable-item class="as-sortable-item">
      <div title="Drag to reorder"  class="as-sortable-item-handle" data-as-sortable-item-handle>
         <i class="icon-resize-vertical"></i>
      </div>
      <div>
         <ir-follower ng-model="follower" extra-parameters="extraParameters"></ir-follower>
      </div>
   </div>
</div>
```

CSS:
```css
/* ************************************** */
/* Mandatory CSS required for ng-sortable */
/* ************************************** */

.as-sortable-item,
.as-sortable-placeholder {
    display: block;
}
.as-sortable-item {
    -ms-touch-action: none;
    touch-action: none;
}
.as-sortable-item-handle {} .as-sortable-placeholder {
    background-color: transparent;
}
.as-sortable-drag {
    position: absolute;
    pointer-events: none;
    z-index: 9999;
    cursor: move;
}
.as-sortable-hidden {
    display: none !important;
}
.as-sortable-un-selectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
/* ******************************************* */
/* Optional CSS, default style for ng-sortable */
/* ******************************************* */

.as-sortable-item,
.as-sortable-placeholder {
    min-height: 20px;
    margin: 1px 2px 5px 1px;
}
.as-sortable-item {
    /* border: solid 0px darkgrey; */
    
    background-color: #ffffff;
}
.as-sortable-item-handle {} .as-sortable-placeholder {
    /* border: 1px dashed darkgrey;*/
    
    box-sizing: border-box;
    /*  background-color: #dbdbdb;*/
}
.as-sortable-drag {
    opacity: .8;
}
.as-sortable-hidden {}
```

JAVASCRIPT:
```javascript
// settings for the sortable follower list
$scope.dragControlListeners = {
    // drag boundary
    containment: '#sortableContainer',
    accept: function(sourceItemHandleScope, destSortableScope) {
        return true;
    }, //override to determine drag is allowed or not. default is true.
    itemMoved: function(event) {},
    orderChanged: function(event) {}
};
```

**Comment by jedatu** [comment]
@nizarmattar Your sample has this structure:
```
<as-sortable>
  <as-sortable-item>
    <as-sortable-item-handle>
      <isolated-directive>
```
Ideally I wanted the isolate directive to _be_ the repeated item and handle, but you can't have two directives on the same element.  

Second to that, I would have preferred that the handle be inside the item directive, which is what @a5hik said he had done.

Third to that, is what you have posted and what I decided to go with for now. Though this isn't ideal, I guess it lets the as-sortable own the entire list manipulation.

**Comment by Darksoulsong** [comment]
I'll post here an example. The handle works inside an isolated scope, but under certain conditions only. I'll show you what does't work. (I'm trying to sort an accordion, btw)

`as-sortable-item-handle` inside local template: doesn't work. It throws `item.index is not a function` error.

  <script type="text/ng-template" id="group-template.html">
    <div class="panel {{panelClass || 'panel-default'}}">
      <div class="panel-heading">
        <h4 class="panel-title">
          <i as-sortable-item-handle class="pull-left glyphicon glyphicon-unchecked"></i>
          <a href tabindex="0" class="accordion-toggle" ng-click="toggleOpen()" uib-accordion-transclude="heading"><span
            ng-class="{'text-muted': isDisabled}">{{heading}}</span></a>
        </h4>
      </div>
      <div class="panel-collapse collapse" uib-collapse="!isOpen">
        <div class="panel-body" ng-transclude></div>
      </div>
    </div>
  </script>

  <div id="accordion" as-sortable="sortableOptions" ng-model="groups">

    <uib-accordion close-others="false">
      <div as-sortable-item ng-repeat="group in groups">
        
        <uib-accordion-group 
          heading="{{group.title}}"  
          template-url="group-template.html"
          >
          
          {{group.content}}

        </uib-accordion-group>

      </div>
    </uib-accordion>
</div>


But THIS DO WORK. (moving the item handle from outside the local template)

    <uib-accordion close-others="false">
      <div as-sortable-item ng-repeat="group in groups">
        
        <uib-accordion-group 
          heading="{{group.title}}"  
          template-url="group-template.html"
          >
          <i as-sortable-item-handle class="pull-left glyphicon glyphicon-unchecked">
          {{group.content}}

        </uib-accordion-group>

      </div>
    </uib-accordion>


Any ideas about how to make the first example work?

**Comment by ninelhodzic** [comment]
Is this solved?

**Comment by robertbl22twc** [comment]
I’ll be working on that component again this quarter. So we’ll see.

**Comment by cybercomkvint** [comment]
I have created a pull-request for this.
Please merge so I can use it in my project ;)

**Comment by a5hik** [comment]
Its merged. Hope I can close this now.

**Comment by rdeutsch** [comment]
I'm hitting this same issue now (handle is within an isolate scope directive, and getting 'item.index is not a function' error.) Looks like there's a fix merged, but it's not yet included in any release. Is there a release planned soon that will include this fix?

**Comment by Jenselme** [comment]
For info, I managed to fix the `item.index is not a function` error with this patch

```patch
--- lib/ng-sortable.js	2016-11-01 14:19:17.516869373 +0100
+++ lib/ng-sortable.js	2016-06-08 00:00:32.000000000 +0200
@@ -260,13 +260,13 @@
         dragItem: function (item) {
 
           return {
-            index: Number.isInteger(item.index) ? item.index : item.index(),
+            index: item.index(),
             parent: item.sortableScope,
             source: item,
             targetElement: null,
             targetElementOffset: null,
             sourceInfo: {
-              index: Number.isInteger(item.index) ? item.index : item.index(),
+              index: item.index(),
               itemScope: item.itemScope,
               sortableScope: item.sortableScope
             },
@@ -290,8 +290,7 @@
               // move the item to a new position
               this.parent = parent;
               // if the source item is in the same parent, the target index is after the source index and we're not cloning
-              var sourceIndex = Number.isInteger(this.source.index) ? this.source.index : this.source.index();
-              if (this.isSameParent() && sourceIndex < index && !this.sourceInfo.sortableScope.cloning) {
+              if (this.isSameParent() && this.source.index() < index && !this.sourceInfo.sortableScope.cloning) {
                 index = index - 1;
               }
               this.index = index;
@@ -846,8 +845,7 @@
             }
             if (!targetScope.sortableScope.options.clone) {
               targetElement[0].parentNode.insertBefore(placeHolder[0], targetElement[0]);
-              var index = Number.isInteger(targetScope.index) ? targetScope.index : targetScope.index();
-              dragItemInfo.moveTo(targetScope.sortableScope, index);
+              dragItemInfo.moveTo(targetScope.sortableScope, targetScope.index());
             }
           }
 
@@ -864,8 +862,7 @@
             }
             if (!targetScope.sortableScope.options.clone) {
               targetElement.after(placeHolder);
-              var index = Number.isInteger(targetScope.index) ? targetScope.index : targetScope.index();
-              dragItemInfo.moveTo(targetScope.sortableScope, index + 1);
+              dragItemInfo.moveTo(targetScope.sortableScope, targetScope.index() + 1);
             }
           }
 
@@ -938,8 +935,7 @@
                 if (placeholderIndex < 0) {
                   insertBefore(targetElement, targetScope);
                 } else {
-                  var index = Number.isInteger(targetScope.index) ? targetScope.index : targetScope.index();
-                  if (placeholderIndex <= index) {
+                  if (placeholderIndex <= targetScope.index()) {
                     insertAfter(targetElement, targetScope);
                   } else {
                     insertBefore(targetElement, targetScope);
```

**Comment by cnickless** [comment]
I just updated to latest version **1.3.8** and am still getting this error:
> Uncaught TypeError: item.index is not a function

Any chance the merged fix can get incorporated in a new release?

**Comment by peterjhart** [comment]
Since this an old, closed issue @cnickless, I opened #387.
